### PR TITLE
Multiuser

### PR DESCRIPTION
**Pull request by lordmathis**
Support for multiple users edditing the same document is working. Still needs some more minor bug fixing

### CODE REVIEW

**Comment by karelbilek** [comment]
o_O

I... don't know what to say

**Comment by karelbilek** [comment]
This is... I mean... it's amazing you actually dug into the code and did all this

I cannot test this and so I will not merge it probably, but all props!

**Comment by lordmathis** [comment]
Yeah I made a mistake. I wanted to merge with my master not this one. That's why I closed it right after I spotted my mistake.

**Comment by karelbilek** [comment]
NP, at least I know what is going on :)

**Pull request closed without merging**
